### ISSUE TITLE
toc.xhtml

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#5]
- You can remove subtitle `<span>`s from the ToC, and also the word "chapter". Then, pull the `z3998:roman` semantic into the `<a>` tag for chapters. See Verne for the pattern to follow: https://github.com/standardebooks/jules-verne_twenty-thousand-leagues-under-the-seas_f-p-walter/blob/master/src/epub/toc.xhtml

It occurred to me that I haven't written up standards for the ToC yet. So much to do...

**Comment by robinwhittleton** [comment]
I’ve copied the Jules Verne example in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/91995ef52bf7ac3c42e8a149b2285749253e6368. This doesn’t move the `z3998:roman` into the link like you suggested; if you want me to do that too then comment back otherwise close it?

As a side note, should the occurrences of the ship name Girondin be marked up as such in the ToC? They are in the chapter titles.

**Comment by acabal** [comment]
Sorry, you're right. Not sure why I was thinking that. You can leave it as committed.

**Comment by robinwhittleton** [comment]
OK! And the italicised _Girondin_ ship name in the ToC?

**Comment by acabal** [comment]
Yes

**Comment by robinwhittleton** [comment]
Cool, fixed that in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/ccfac25a5d4b3eb0776ed39847216610a1111a15. That’s everything in this issue covered.
